# **Diccionarios**

In [1]:
# Definition of countries and capital
countries = ['spain', 'france', 'germany', 'norway']
capitals = ['madrid', 'paris', 'berlin', 'oslo']
 
# Get index of 'germany': ind_ger
ind_ger = countries.index('germany')
 
# Use ind_ger to print out capital of Germany
print(capitals[ind_ger])

berlin

In [4]:
# Definition of countries and capital
countries = ['spain', 'france', 'germany', 'norway']
capitals = ['madrid', 'paris', 'berlin', 'oslo']
 
# From string in countries and capitals, create dictionary europe
europe = { 'spain':'madrid', 'france': 'paris', 'germany': 'berlin','norway':'oslo'}
 
# Print europe
print(europe)

{'spain': 'madrid', 'france': 'paris', 'germany': 'berlin', 'norway': 'oslo'}

In [2]:
# Definition of dictionary
europe = {'spain':'madrid', 'france':'paris', 'germany':'berlin', 'norway':'oslo' }
 
# Print out the keys in europe
print(europe.keys())
 
# Print out value that belongs to key 'norway'
print('\r')
print(europe['norway'])

dict_keys(['spain', 'france', 'germany', 'norway'])

oslo

In [5]:
# Definition of dictionary
europe = {'spain':'madrid', 'france':'paris', 'germany':'berlin', 'norway':'oslo' }
 
# Add italy to europe
europe['italy']= 'rome'
 
# Print out italy in europe
print('italy' in europe)
print('\r')
# Add poland to europe
europe['poland']= 'warsaw'
 
# Print europe
print(europe)

True

{'spain': 'madrid', 'france': 'paris', 'germany': 'berlin', 'norway': 'oslo', 'italy': 'rome', 'poland': 'warsaw'}

In [6]:
# Definition of dictionary
europe = {'spain':'madrid', 'france':'paris', 'germany':'bonn',
          'norway':'oslo', 'italy':'rome', 'poland':'warsaw',
          'australia':'vienna' }
 
# Update capital of germany
europe['germany'] = 'berlin'
 
# Remove australia
del(europe['australia'])
 
# Print europe
print(europe)

{'spain': 'madrid', 'france': 'paris', 'germany': 'berlin', 'norway': 'oslo', 'italy': 'rome', 'poland': 'warsaw'}

In [7]:
# Dictionary of dictionaries
europe = { 'spain': { 'capital':'madrid', 'population':46.77 },
           'france': { 'capital':'paris', 'population':66.03 },
           'germany': { 'capital':'berlin', 'population':80.62 },
           'norway': { 'capital':'oslo', 'population':5.084 } }
 
 
# Print out the capital of France
print(europe['france']['capital'])
 
# Create sub-dictionary data
data = {'capital':'rome', 'population':59.83}
 
# Add data to europe under key 'italy'
europe['italy']=data
 
# Print europe
print('\r')
print(europe)

paris

{'spain': {'capital': 'madrid', 'population': 46.77}, 'france': {'capital': 'paris', 'population': 66.03}, 'germany': {'capital': 'berlin', 'population': 80.62}, 'norway': {'capital': 'oslo', 'population': 5.084}, 'italy': {'capital': 'rome', 'population': 59.83}}

# **PANDAS**

In [8]:
# Pre-defined lists
names = ['United States', 'Australia', 'Japan', 'India', 'Russia', 'Morocco', 'Egypt']
dr =  [True, False, False, False, True, True, True]
cpc = [809, 731, 588, 18, 200, 70, 45]
 
# Import pandas as pd
import pandas as pd
 
# Create dictionary my_dict with three key:value pairs: my_dict
my_dict = {'country':names, 'drives_right':dr, 'cars_per_cap':cpc}
 
# Build a DataFrame cars from my_dict: cars
cars = pd.DataFrame(my_dict)
 
# Print cars
cars

         country  drives_right  cars_per_cap
0  United States          True           809
1      Australia         False           731
2          Japan         False           588
3          India         False            18
4         Russia          True           200
5        Morocco          True            70
6          Egypt          True            45

In [9]:
# Build cars DataFrame
names = ['United States', 'Australia', 'Japan', 'India', 'Russia', 'Morocco', 'Egypt']
dr =  [True, False, False, False, True, True, True]
cpc = [809, 731, 588, 18, 200, 70, 45]
cars_dict = { 'country':names, 'drives_right':dr, 'cars_per_cap':cpc }
cars = pd.DataFrame(cars_dict)
print(cars)
 
# Definition of row_labels
row_labels = ['US', 'AUS', 'JPN', 'IN', 'RU', 'MOR', 'EG']
 
# Specify row labels of cars
cars.index=row_labels
 
# Print cars again
print('\r')
print(cars)

         country  drives_right  cars_per_cap
0  United States          True           809
1      Australia         False           731
2          Japan         False           588
3          India         False            18
4         Russia          True           200
5        Morocco          True            70
6          Egypt          True            45

           country  drives_right  cars_per_cap
US   United States          True           809
AUS      Australia         False           731
JPN          Japan         False           588
IN           India         False            18
RU          Russia          True           200
MOR        Morocco          True            70
EG           Egypt          True            45

In [10]:
cars.to_excel('cars.xlsx')

In [11]:
cars = pd.read_excel('cars.xlsx', index_col = 0)
 
# Print out country column as Pandas Series
print(cars['country'])
print('\r')
# Print out country column as Pandas DataFrame
print(cars[['country']])
 
print('\r')
# Print out DataFrame with country and drives_right columns
print(cars[['country','drives_right']])

US     United States
AUS        Australia
JPN            Japan
IN             India
RU            Russia
MOR          Morocco
EG             Egypt
Name: country, dtype: object

           country
US   United States
AUS      Australia
JPN          Japan
IN           India
RU          Russia
MOR        Morocco
EG           Egypt

           country  drives_right
US   United States          True
AUS      Australia         False
JPN          Japan         False
IN           India         False
RU          Russia          True
MOR        Morocco          True
EG           Egypt          True

In [12]:
# Print out first 3 observations
print(cars[0:4])
print('\r')
 
# Print out fourth, fifth and sixth observation
print(cars[3:6])

           country  drives_right  cars_per_cap
US   United States          True           809
AUS      Australia         False           731
JPN          Japan         False           588
IN           India         False            18

     country  drives_right  cars_per_cap
IN     India         False            18
RU    Russia          True           200
MOR  Morocco          True            70

In [13]:
# Print out observation for Japan
print(cars.loc['JPN'])
print('\r')
print(cars.iloc[2])
print('\r')
# Print out observations for Australia and Egypt
print(cars.loc[['AUS', 'EG']])

country         Japan
drives_right    False
cars_per_cap      588
Name: JPN, dtype: object

country         Japan
drives_right    False
cars_per_cap      588
Name: JPN, dtype: object

       country  drives_right  cars_per_cap
AUS  Australia         False           731
EG       Egypt          True            45

In [14]:
# Print out drives_right value of Morocco
print(cars.loc['MOR', 'drives_right'])
print('\r')
 
# Print sub-DataFrame
print(cars.loc[['RU', 'MOR'], ['country', 'drives_right']])

True

     country  drives_right
RU    Russia          True
MOR  Morocco          True

In [15]:
# Print out drives_right column as Series
print(cars['drives_right'])
 
# Print out drives_right column as DataFrame
print(cars[['drives_right']])
 
# Print out cars_per_cap and drives_right as DataFrame
print(cars.loc[:,['cars_per_cap','drives_right']])

US      True
AUS    False
JPN    False
IN     False
RU      True
MOR     True
EG      True
Name: drives_right, dtype: bool
     drives_right
US           True
AUS         False
JPN         False
IN          False
RU           True
MOR          True
EG           True
     cars_per_cap  drives_right
US            809          True
AUS           731         False
JPN           588         False
IN             18         False
RU            200          True
MOR            70          True
EG             45          True

# **Comparasion Operators**

In [16]:
# Define variables
my_kitchen = 18.0
your_kitchen = 14.0
 
# my_kitchen bigger than 10 and smaller than 18?
print(my_kitchen > 10 and my_kitchen < 18)
 
# my_kitchen smaller than 14 or bigger than 17?
print(my_kitchen < 14 or my_kitchen > 17)
 
# Double my_kitchen smaller than triple your_kitchen?
print( my_kitchen *2 > your_kitchen*3)

False
True
False

In [17]:
# Create arrays
import numpy as np
my_house = np.array([18.0, 20.0, 10.75, 9.50])
your_house = np.array([14.0, 24.0, 14.25, 9.0])
 
# my_house greater than 18.5 or smaller than 10
print(np.logical_or(my_house > 18.5, 
               your_house < 10))
 
# Both my_house and your_house smaller than 11
print(np.logical_and(my_house < 11, 
               your_house < 11))

[False  True False  True]
[False False False  True]

In [18]:
# Define variables
room = "kit"
area = 14.0
 
# if statement for room
if room == "kit" :
    print("looking around in the kitchen.")
 
# if statement for area
if area > 15:
    print('big place!')

looking around in the kitchen.

In [19]:
# Define variables
room = "kit"
area = 14.0
 
# if-else construct for room
if room == "kit" :
    print("looking around in the kitchen.")
else :
    print("looking around elsewhere.")
 
print('\r')
# if-else construct for area
if area > 15 :
    print("big place!")
else:
    print('pretty small.')

looking around in the kitchen.

pretty small.

In [20]:
# Define variables
room = "bed"
area = 14.0
 
# if-elif-else construct for room
if room == "kit" :
    print("looking around in the kitchen.")
elif room == "bed":
    print("looking around in the bedroom.")
else :
    print("looking around elsewhere.")
 
print('\r')
# if-elif-else construct for area
if area > 15 :
    print("big place!")
elif area > 10:
    print('medium size, nice!')
else :
    print("pretty small.")

looking around in the bedroom.

medium size, nice!

# **Filtering pandas DataFrames**

In [21]:
# Extract drives_right column as Series: dr
dr = cars['drives_right']
 
# Use dr to subset cars: sel
sel = cars[dr]
 
# Print sel
print(sel)

           country  drives_right  cars_per_cap
US   United States          True           809
RU          Russia          True           200
MOR        Morocco          True            70
EG           Egypt          True            45

In [22]:
# Convert code to a one-liner
sel = cars[cars['drives_right']]
# Print sel
print(sel)

           country  drives_right  cars_per_cap
US   United States          True           809
RU          Russia          True           200
MOR        Morocco          True            70
EG           Egypt          True            45

 # **While**

while condition:
  
  
  
  expression



Repite hasta que se cumpla la condición

In [23]:
error = 50  
 
while error >1:
  error = error / 4
  print(error)

12.5
3.125
0.78125

In [ ]:
# Initialize offset
offset = 8
 
# Code the while loop
while offset != 0:
    print('correcting...')
    offset = offset -1
    print(offset)

correcting...
7
correcting...
6
correcting...
5
correcting...
4
correcting...
3
correcting...
2
correcting...
1
correcting...
0

In [24]:
# Initialize offset
offset = -6
 
# Code the while loop
while offset != 0 :
    print("correcting...")
    if offset > 0 :
      offset = offset - 1
    else : 
     offset =  offset + 1   
    print(offset)

correcting...
-5
correcting...
-4
correcting...
-3
correcting...
-2
correcting...
-1
correcting...
0

# **Loop**

for var in seq:




  expression

In [25]:
fam = [1.73, 1.68, 1.71, 1.89]
for height in fam : 
    print(height)

1.73
1.68
1.71
1.89

In [26]:
fam = [1.73, 1.68, 1.71, 1.89]
for index, height in enumerate(fam) :
    print("person " + str(index) + ": " + str(height))

person 0: 1.73
person 1: 1.68
person 2: 1.71
person 3: 1.89

In [27]:
# areas list
areas = [11.25, 18.0, 20.0, 10.75, 9.50]
 
# Code the for loop
for a in areas:
    print(a)

11.25
18.0
20.0
10.75
9.5

In [28]:
# areas list
areas = [11.25, 18.0, 20.0, 10.75, 9.50]
 
# Change for loop to use enumerate() and update print()
for index, a in enumerate(areas) :
    print('room ' + str(index) + ": " + str(a))

room 0: 11.25
room 1: 18.0
room 2: 20.0
room 3: 10.75
room 4: 9.5

In [29]:
# areas list
areas = [11.25, 18.0, 20.0, 10.75, 9.50]
 
# Code the for loop
for index, area in enumerate(areas) :
    print("room " + str(index+1) + ": " + str(area))

room 1: 11.25
room 2: 18.0
room 3: 20.0
room 4: 10.75
room 5: 9.5

In [30]:
# house list of lists
house = [["hallway", 11.25], 
         ["kitchen", 18.0], 
         ["living room", 20.0], 
         ["bedroom", 10.75], 
         ["bathroom", 9.50]]
         
# Build a for loop from scratch
for x in house :
    print("the " + x[0] + " is " + str(x[1]) + " sqm")

the hallway is 11.25 sqm
the kitchen is 18.0 sqm
the living room is 20.0 sqm
the bedroom is 10.75 sqm
the bathroom is 9.5 sqm